### ISSUE TITLE
Need update from Microsoft.CodeAnalysis.VisualBasic.Workspaces 2.9.0 to 2.10.0

### ISSUE THREAD

**Issue by ramoneeza** [daveaglick/Buildalyzer#103]
Nuget gives error when installing Buildalizer.WorkSpaces.
A reference to VisualBasic.Workspaces 2.9.0 is fixed and it would by necessary to update to 2.10.0.

(Or create two separate packages... one for CSharp and another to VB)

**Comment by daveaglick** [comment]
I'm not sure I understand. Why is the reference to `Microsoft.CodeAnalysis.VisualBasic.Workspaces` version 2.9.0 causing problems? Do you already have version 2.10.0 installed and NuGet is complaining that installing Buildalyzer would downgrade? Any chance you could post the NuGet install log with the error?

**Comment by Mobrockers** [comment]
@daveaglick I just hit the same issue, it's because we use Microsoft.CodeAnalysis.CSharp ourselves. We resolved it as suggested by visual studio, by explicitly installing Microsoft.CodeAnalysis.Common in our project:

![image](https://user-images.githubusercontent.com/3595932/64065835-0e6d4d80-cc13-11e9-888f-3c59b1f3ec76.png)

**Comment by Mobrockers** [comment]
I forgot to comment but there is too big a difference in signatures for Microsoft.CodeAnalysis.Common 3.4 to be compatible with Microsoft.CodeAnalysis.CSharp.Workspaces 2.9 so I actually never did fix the problem.

Because we use Microsoft.CodeAnalysis.CSharp with an up-to-date version we are unable to use Buildalyzer.Workspaces. I would very much like to be able to use it.

**Comment by daveaglick** [comment]
Fixed by #124
