### ISSUE TITLE
AnalyzerManagerOptions.ProjectTransformer is not working

### ISSUE THREAD

**Issue by sapsari** [daveaglick/Buildalyzer#114]
ProjectTransformer is passed down to ProjectFile but it is not being used there

**Comment by sapsari** [comment]
Also noticed that project file is passed as an argument for dotnet command in ProjectAnalyzer.cs line 270 (in ProjectAnalyzer.GetCommand()). Would it be possible to transform project file virtually?

**Comment by daveaglick** [comment]
Thanks for the report - everything went through a huge rewrite and refactoring in 2.0 and that’s probably where this bug came from. I’ll take a closer look.

Can you expand on “transform the project file virtually”? You mean you want to make in-memory changes to the project file and have those impact the build?

Unfortunately I’m not sure we can do that...at least not without writing out a new temporary project file. In fact, we might not even be able to use the transformer any more. The big change from 1.x to 2.x was shelling out to MSBuild instead of calling it through the API. When using the API you could pass a “virtual” project file, but when shelling out it needs a file on disk to read.

**Comment by sapsari** [comment]
> Can you expand on “transform the project file virtually”? You mean you want to make in-memory changes to the project file and have those impact the build?
> 
Yeah, that's what I meant; without changing the project file on disk.

I tried to fix this issue myself but failed. Buildalyzer itself uses the transformed project properties (ProjectFile._projectElement is modified) but dotnet command uses the project file on the disk, so transformation has no effect on it.

So if the transformer is no longer functional, I can use a temporary project file.

**Comment by sapsari** [comment]
For those having the same issue, here is how I solved it with a temp project creation:
https://gist.github.com/sapsari/fbe93f1f245d012954b61f3744471f88

You can commit changes to the workspace (meaning modify source files) after deleting the project

**Comment by daveaglick** [comment]
> but dotnet command uses the project file on the disk, so transformation has no effect on it

Yep, that's exactly the issue. When Buildalyzer switched to shelling out we lost the ability to feed a virtual project file to MSBuild. The tradeoff is more correctness and stability but we loose any capabilities afforded by direct MSBuild API use.

> I can remove IProjectTransformer then crate a pull request if that is gonna be your design decision

Thanks for the offer! Sorry it took so long to get back to this. I was prepping a release anyway so I went ahead and ripped out the transformer while I was in there.
