### ISSUE TITLE
`net6.0` support pulled out, possibly due to a bad merge

### ISSUE THREAD

**Issue by brettfo** [daveaglick/Buildalyzer#201]
In commit a3312a95f17a21c9575a077e61706b82b59be6f8 on Feb 16 support for `net6.0` was added and the Roslyn packages were updated to version 4.0.1, but a few hours later in commit bbbd23a3a11c24702f7f3e5a751bd12224ce2e9d that support was removed, possibly due to a failed merge.

**Comment by brettfo** [comment]
The explicit `net6.0` support isn't too worrysome, but the Roslyn downgrade from 4.0.1 to 3.11.0 is.

**Comment by daveaglick** [comment]
Ah, gotcha. So AFAIK Roslyn 4.x still targets .NET Core 3.1/.NET Standard 2.0, right? Roslyn is only used in the Buildalyzer.Workspaces package, and upsetting Roslyn won't break the .NET Core 3.1 target anyway, so that shouldn't be a problem to update Roslyn without updating the target.

So now I'm curious what's not working under Roslyn 3.x? Is it just that the Workspace you get back isn't compatible with a more recent Roslyn version in the calling app?

**Comment by brettfo** [comment]
The Roslyn completion APIs aren't perfectly compatible, e.g., a Buildalyzer workspace (backed by Roslyn 3.11.0) when passed to the `4.0.1` version of [this](https://github.com/dotnet/roslyn/blob/53b34d4753325c029152a34c9be485970104f0d9/src/Workspaces/Core/Portable/Recommendations/Recommender.cs#L17) method results in a `InvalidOperationException`, but if the Buildalyzer (3.11.0) workspace is passed to the Roslyn `3.11.0` version of that function (actually, the 3.11.0 version has the suffix `Async`) then everything works, but my use case requires Roslyn 4.0.1.

**Comment by daveaglick** [comment]
Gotcha, so some compat issues across the major version line there. Not a problem - since the targeting still lines up, I don't see why we couldn't bump the Roslyn versions to latest. I'll play around with that tomorrow and ship it quick as long as it doesn't break anything else.

**Comment by daveaglick** [comment]
New release with updated Roslyn dependencies for `Buildalyzer.Buildalyzer.Workspaces` is out. I'll close this issue for now, but please let me know if the new release does/doesn't work for you.
