### ISSUE TITLE
Don't include newlines when formatting logs

### ISSUE THREAD

**Issue by kentcb** [daveaglick/Buildalyzer#30]
A small thing, really, but kinda annoying. Formatting a log entry via the `ILogger.Log` `formatter` parameter adds a new line to the end. This makes it difficult to integrate with some logging solutions that _also_ add a new line for you when you invoke them. Wouldn't it be better to just return the string without a new line and let the caller handle it?

**Comment by daveaglick** [comment]
That's a totally reasonable request. First thought is change it so the new line is added if writing to a TextWriter but omitted if using an ILoggerFactory.

**Comment by daveaglick** [comment]
_Finally_ looking a little closer at this.

The only place we use the `formatter` is in the `ILogger` that gets created when a `TextWriter` is provided. My original thinking was that if you're passing in a `TextWriter` you're going to need a little extra help formatting, like adding the severity and new lines. Otherwise, I would have expected most logging solution to provide their own `ILoggerProvider` and `ILogger` implementations.

After looking closer, I'm concerned that just sending the message without formatting or new lines to the `TextWriter` wouldn't provide any context beyond the message. How would the consumer of the `TextWriter` know where one message ended and another one started or whether it's an error, warning, or informational?

**Comment by daveaglick** [comment]
Given how much Buildalyzer has changed since opening this, including log messages now coming from the console via the out-of-process MSBuild, I'm wondering if this issue is still valid. I'm going to go ahead and close it for now - please do open a new issue if it turns out this is still a problem that needs looking at.
