### ISSUE TITLE
Please release a new nuget package

### ISSUE THREAD

**Issue by johtela** [daveaglick/Buildalyzer#62]
Hi Dave,

I am porting my [literate programming tool](https://github.com/johtela/LiterateProgramming) to .NET Core and found that your library is a great replacement for MSBuildWorkspace which sadly is absent in netcore. However, the version available as nuget package gives a lot of build errors which are fixed in the latest commit on GitHub. 

Can you please release a new version of the nuget package, so I can get the latest and greatest version cleanly imported to my project?

Thanks,
Tommi

**Comment by daveaglick** [comment]
I've been trying to get a new package out the door for the last few weeks! :rofl: 

If you check the commit history you'll see I've been working hard on tackling MSBuild build problems under various conditions (hopefully some of which are the issues you've encountered). The challenge has been that as soon as I think I've got it nice and stable, I discover another edge case that requires fixing. I _think_ I'm getting close though (for real this time!).

The good news is that Buildalyzer is _way_ better now than the current release, including a complete overhaul of the API. When I do finish up the current push, it'll go out as version 1.0. The bad news is that I'm not quite there yet and am preparing for a week in the wilderness away from my computer (and even Internet for that matter). You'll need to wait until at least the week after next for that 1.0 version to drop, unless you feel like cloning and building from source (which I think should work fine, but can't guarantee since I'm still in the process of setting up CI).

**Comment by daveaglick** [comment]
If you're comfortable building from source and really want to get a release of your own package out that references a custom build of Buildalyzer, I suggest placing your custom build of the Buildalyzer package on a personal MyGet feed and having your package reference that until I get 1.0 out the door and on the official NuGet feed.

**Comment by dfederm** [comment]
Or just submodule and build from source for now :-)

**Comment by johtela** [comment]
Thanks for the quick replies. I have included Buildalyzer as a source reference and that is working fine, but I would prefer to have all dependencies as nuget packages.

I can wait for a couple of weeks for the official release. I am not in a hurry. It's a good idea be off-grid for a while :-) Thanks for the great job you have done with the library. I have come to appreciate how hairy MSBuild stuff is, so I understand it takes time to get everything working.

**Comment by robsonj** [comment]
+1 for this, just ran into the same issues

**Comment by daveaglick** [comment]
Buildalyzer 1.0.0 was released to NuGet last night. Give it a spin and hopefully it resolves each of your issues. If not, please open new issues so we can start working on patches.

Also FYI - the new version has significant API changes. Most of the concepts are the same, but things have been shuffled. Mostly to make it more flexible and also to account for the concept of multiple build targets. The biggest conceptual difference is that `ProjectAnalyzer` no longer stores build results and instead returns a new result object for builds. Better documentation is forthcoming, but I wanted to get the release out there ASAP since it's been a while.

**Comment by johtela** [comment]
Tested the version 1.0.0 with few projects on Windows; both .NET Core and Framework. No build errors anymore, so I am happy 😃

**Comment by daveaglick** [comment]
Yay!
