### ISSUE TITLE
Incorrect OutputKind in AdhocWorkspace

### ISSUE THREAD

**Issue by JosephWoodward** [daveaglick/Buildalyzer#7]
I've noticed when loading a project into the AdHocWorkspace the `OutputKind` enum is always set to `ConsoleApplication` (see below as an example).

Having looked through the Buildalyzer source code can't see where the project type is inferred, leading me to assume the reason it's set to `ConsoleApplication` is because it's the first property in the `OutputKind` enum so defaults to that.

```csharp
var analyzer = new Analyzer();
var projectAnalyzer = analyzer.GetProject(@"../demo/ExampleDllLibrary.csproj");
var workspace = projectAnalyzer.GetWorkspace();
var project = workspace.CurrentSolution.Projects.FirstOrDefault(x => x.AssemblyName == "ExampleDllLibrary");
OutputKind kind = project.CompilationOptions.OutputKind;
Console.WriteLine(kind); // ConsoleApplication
```

Not being too savvy with the MSBuild API I'm wondering if you can point me in the right direction of where I'd be able to get this information so I can create a PR to fix it?

**Comment by daveaglick** [comment]
Good catch. Looks like the MSBuild property `OutputType` is what you want. It has possible values of "Library", "Exe", "Module", or "Winexe". Those look like they map pretty well to the `OutputKind` enum in Roslyn.

You can get the MSBuild property from the MSBuild `ProjectInstance` instance (`ProjectAnalyzer.CompiledProject` or the return value of `Compile()`) like this:
```
string outputType = analyzer.CompiledProject?.GetPropertyValue("OutputType");
```

Be sure to check for null on the `ProjectAnalyzer.CompiledProject` property since it won't be set if compilation failed.

**Comment by JosephWoodward** [comment]
So you have to compile the project before you can figure out its output type? Can it not infer it from the .csproj file?

**Comment by daveaglick** [comment]
Hmm... Might be available on the `Project` instance after `Load()`.

**Comment by JosephWoodward** [comment]
Yup, there it is! Much better, thanks. Currently putting together a PR now.

**Comment by JosephWoodward** [comment]
There we go, #8 adds `CompilationOptions` and is ready for review.
