### ISSUE TITLE
DefineConstants not worked in compilation

### ISSUE THREAD

**Issue by itn3000** [daveaglick/Buildalyzer#86]
# Environment

* dotnet sdk 2.1.402
* Buildalyzer: 2.1.0
* windows8.1 x64

# Steps to reproduce

1. unpack [buildalyzertest.constants.zip](https://github.com/daveaglick/Buildalyzer/files/2472339/buildalyzertest.constants.zip)
2. move "buildalyzertest.constants/buildalyzertest.constants"
3. run `dotnet run`

"buildalyzertest.constants/buildalyzertest.constants" does

1. get project instance of sandboxproject
2. get workspace by `ProjectAnalyzerExtensions.GetWorkspace()`
2. enumerate class names

# Expected Result

```
ns=sandboxproject.X1, X1
ns=sandboxproject.X3, X3
ns=sandboxproject.Program, Program
Hello World!
```

it means sandboxproject.X1(surrounded by `DEF1` symbol) is included in Compilation.Assembly.

# Actual Result

```
ns=sandboxproject.X3, X3
ns=sandboxproject.Program, Program
Hello World!
```

sandboxproject.X1 is not included in Compilation.Assembly.
`DEF1` seems to be not defined in compilation.

Additionally, do `dotnet build` in sandboxproject by hand and analyze output assembly by [dnSpy](https://github.com/0xd4d/dnSpy),
sandboxproject.X1 is included in symbols.

**Comment by daveaglick** [comment]
I can see where the problem is here. The constant will get defined correctly during the MSBuild pass when we build the project(s) and get the resulting project files, but then in `.GetWorkspace()` it passes those project files along with some other rudimentary information to Roslyn but doesn't pass the defined constants.

To get this to work I'll need to make sure any build constants get passed to Roslyn. This is tricky because I can't just pull those right out of the project file - they've got to come from the _result_ of the build since they could get redefined or even based on other constants. I'll start looking into this.

**Comment by daveaglick** [comment]
This is now resolved and will ship with the next release.
